# Generated by Django 5.1.6 on 2025-03-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('numero_muestra', models.CharField(max_length=50)),
                ('nivel_agua', models.FloatField()),
                ('ph', models.FloatField()),
                ('toc', models.FloatField(help_text='Carbono Orgánico Total (mg/L)')),
                ('dqo', models.FloatField(help_text='Demanda Química de Oxígeno (mg/L)')),
                ('r', models.FloatField()),
                ('ssed', models.FloatField()),
                ('ud_ph', models.FloatField()),
                ('temperatura', models.FloatField(help_text='Temperatura en °C')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('supervisor', models.CharField(max_length=100)),
            ],
        ),
    ]
