# Generated by Django 5.1.6 on 2025-04-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0005_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='portadas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
